### ISSUE TITLE
TargetInvocationException: Failed to invoke filter: includeFile()

### ISSUE THREAD

**Issue by netProgrammer** [NetCoreTemplates/templates#1]
After
`$ npm install -g @servicestack/cli
$ dotnet-new templates ProjectName`
I call `dotnet run` and result view-source: ... :5000/ after opening in browser:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Templates</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {{#if debug}}<script>null<pre class='error'>
TargetInvocationException: Failed to invoke filter: includeFile()
   at ServiceStack.Templates.PageResult.EvaluateAsync(PageVariableFragment var, TemplateScopeContext scope, CancellationToken token)
   at ServiceStack.Templates.PageResult.WriteVarAsync(TemplateScopeContext scope, PageVariableFragment var, CancellationToken token)
   at ServiceStack.Templates.PageResult.WriteToAsyncInternal(Stream outputStream, CancellationToken token)
   at ServiceStack.Templates.PageResult.WriteToAsync(Stream responseStream, CancellationToken token)
   at ServiceStack.TemplatePageHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)

Inner Exceptions:
NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Templates.TemplateProtectedFilters.ResolveFile(IVirtualPathProvider virtualFiles, String fromVirtualPath, String virtualPath)
   at ServiceStack.Templates.TemplateProtectedFilters.ResolveFile(String filterName, TemplateScopeContext scope, String virtualPath)
   at ServiceStack.Templates.TemplateProtectedFilters.includeFile(TemplateScopeContext scope, String virtualPath)
   at ServiceStack.Templates.PageResult.EvaluateAsync(PageVariableFragment var, TemplateScopeContext scope, CancellationToken token)
</pre>
```

**Comment by netProgrammer** [comment]
Sorry my fault `nuget locals all -clear `
